/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package io.zdp.node.ui;

/**
 *
 * @author sxn144
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        serverUuid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        serverPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        serverType = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        nodeLogs = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        httpLogs = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnOpenLogs = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/server.png"))); // NOI18N
        jLabel1.setText("Server UUID:");

        serverUuid.setEditable(false);

        jLabel2.setText("Port:");

        serverPort.setEditable(false);

        jLabel3.setText("Type:");

        serverType.setEditable(false);

        jSplitPane1.setDividerLocation(190);
        jSplitPane1.setDividerSize(15);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);

        nodeLogs.setEditable(false);
        nodeLogs.setBackground(new java.awt.Color(0, 0, 0));
        nodeLogs.setColumns(20);
        nodeLogs.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        nodeLogs.setForeground(new java.awt.Color(51, 255, 51));
        nodeLogs.setRows(5);
        jScrollPane1.setViewportView(nodeLogs);

        jSplitPane1.setTopComponent(jScrollPane1);

        httpLogs.setEditable(false);
        httpLogs.setBackground(new java.awt.Color(0, 0, 0));
        httpLogs.setColumns(20);
        httpLogs.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        httpLogs.setForeground(new java.awt.Color(51, 255, 51));
        httpLogs.setRows(5);
        jScrollPane2.setViewportView(httpLogs);

        jSplitPane1.setRightComponent(jScrollPane2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/server_chart.png"))); // NOI18N
        jButton1.setText("Server Info");

        btnOpenLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder_table.png"))); // NOI18N
        btnOpenLogs.setText("Open logs folder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serverUuid, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serverPort, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serverType, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenLogs)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(serverUuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(serverPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(serverType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpenLogs)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnOpenLogs;
    public javax.swing.JTextArea httpLogs;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JTextArea nodeLogs;
    public javax.swing.JTextField serverPort;
    public javax.swing.JTextField serverType;
    public javax.swing.JTextField serverUuid;
    // End of variables declaration//GEN-END:variables
}
